#@ load("@ytt:data", "data")
---
fullName:
  location: global
  name: #@ data.values.name
objectMeta:
  annotations: #@ data.values.annotations
  description: #@ data.values.description
  labels: #@ data.values.labels
spec:
  clusterGroupName: #@ data.values.cluster_group
  provisionedcluster:
    accountName: #@ data.values.account_credential
    cloudProviderConfig:
      awsConfig:
        controlPlaneVmFlavor: #@ data.values.aws.machine_type
        network_spec:
          vpc:
            cidr_block: 10.0.0.0/16
        region: #@ data.values.aws.region
        sshKeyName: #@ data.values.aws.ssh_key_name
    highAvailability: false
    networkConfig:
      podCidr: 192.168.0.0/16
      serviceCidr: 10.96.0.0/12
    nodePool:
    - fullName:
        clusterName: #@ data.values.name
        location: global
        name: #@ "{}-node-pool".format(data.values.name)
        provisionedclusterName: #@ data.values.name
      spec:
        cloudProviderConfig:
          awsConfig:
            instanceType: #@ data.values.aws.machine_type
        version: ""
        workerNodeCount: 1
    version: ""
typeMeta:
  kind: Cluster
  package: vmware.olympus.v1alpha.cluster
  version: v1alpha

