#@ load("@ytt:data", "data")
---
fullName:
  name: #@ data.values.name
objectMeta:
  annotations: #@ data.values.annotations
  description: #@ data.values.description
  labels: #@ data.values.labels
typeMeta:
  kind: ClusterGroup
  package: vmware.olympus.v1alpha.clustergroup
  version: v1alpha

